# Generated by Django 5.2.1 on 2025-05-31 03:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('preco', models.DecimalField(decimal_places=2, max_digits=10)),
                ('foto', models.ImageField(upload_to='produtos/')),
                ('categoria', models.CharField(choices=[('CASA', 'Para o nosso lar'), ('LUA_DE_MEL', 'Para nossa lua de mel')], default='CASA', max_length=20)),
                ('subcategoria', models.CharField(blank=True, choices=[('UTENSILIOS', 'Utensílios de cozinha'), ('ELETRO', 'Eletrodomésticos e Eletroportáteis'), ('CAMA_MESA_BANHO', 'Itens cama, mesa e banho'), ('MOVEIS', 'Móveis')], max_length=40, null=True)),
            ],
        ),
    ]
