# Generated by Django 5.2.1 on 2025-06-05 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produto',
            name='subcategoria',
            field=models.CharField(blank=True, choices=[('UTENSILIOS', 'Utensílios de cozinha'), ('ELETRO', 'Eletrodomésticos e Eletroportáteis'), ('CAMA_MESA_BANHO', 'Itens cama, mesa e banho'), ('MOVEIS', 'Móveis'), ('PASSEIOS', 'Passeios'), ('REFEICOES', 'Refeições'), ('PASSAGENS', 'Passagens'), ('HOSPEDAGENS', 'Hospedagens')], max_length=40, null=True),
        ),
    ]
