# Generated by Django 5.2.1 on 2025-06-07 02:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0002_alter_produto_subcategoria'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='cotas',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
