# Generated by Django 5.2.1 on 2025-06-01 23:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0003_confirmacao'),
    ]

    operations = [
        migrations.AddField(
            model_name='confirmacao',
            name='comparecera',
            field=models.BooleanField(default=True),
        ),
    ]
