# Generated by Django 5.2.1 on 2025-06-01 23:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0004_confirmacao_comparecera'),
    ]

    operations = [
        migrations.AlterField(
            model_name='confirmacao',
            name='comparecera',
            field=models.BooleanField(choices=[('SIM', 'SIM'), ('NÃO', 'NÃO')], default='SIM', max_length=3),
        ),
    ]
