# Generated by Django 5.2.1 on 2025-06-02 00:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0005_alter_confirmacao_comparecera'),
    ]

    operations = [
        migrations.AlterField(
            model_name='confirmacao',
            name='comparecera',
            field=models.CharField(choices=[('NÃO', 'NÃO'), ('SIM', 'SIM')], default='SIM', max_length=3),
        ),
    ]
