# Generated by Django 5.2.1 on 2025-06-02 00:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0007_alter_confirmacao_comparecera'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='confirmacao',
            name='comparecera',
        ),
    ]
