# Generated by Django 5.2.1 on 2025-06-02 02:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0008_remove_confirmacao_comparecera'),
    ]

    operations = [
        migrations.AddField(
            model_name='confirmacao',
            name='comparecera',
            field=models.CharField(choices=[('SIM', 'Sim'), ('NAO', 'Não')], default='NAO', max_length=3),
        ),
    ]
