# Generated by Django 5.2.1 on 2025-06-02 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0010_remove_confirmacao_comparecera'),
    ]

    operations = [
        migrations.AddField(
            model_name='confirmacao',
            name='comparecera',
            field=models.BooleanField(default=True),
        ),
    ]
