# Generated by Django 5.2.1 on 2025-06-02 22:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0012_remove_confirmacao_comparecera'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='confirmacao',
            name='nome',
        ),
        migrations.AddField(
            model_name='confirmacao',
            name='comparecera',
            field=models.CharField(choices=[('SIM', 'Sim'), ('NAO', 'Não')], default='SIM', max_length=3),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='confirmacao',
            name='convidado',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='usuarios.convidado'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Acompanhante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('telefone', models.CharField(max_length=20)),
                ('comparecera', models.CharField(choices=[('SIM', 'Sim'), ('NAO', 'Não')], max_length=3)),
                ('confirmacao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='acompanhantes', to='usuarios.confirmacao')),
            ],
        ),
    ]
