# Generated by Django 5.2.1 on 2025-06-02 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0013_remove_confirmacao_nome_confirmacao_comparecera_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='confirmacao',
            name='convidado',
        ),
        migrations.AddField(
            model_name='confirmacao',
            name='nome',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Acompanhante',
        ),
    ]
